import {activityUtils, actorUtils, constants, dialogUtils, effectUtils, genericUtils, itemUtils, rollUtils, socketUtils, tokenUtils, workflowUtils} from '../../../../../utils.js';
import {determineSuperiorityDie, superiorityHelper} from '../../../../2014/classFeatures/fighter/battleMaster/superiorityDice.js';
import {selectPendingDie, satisfiesMovementRequirement} from '../../../../../lib/utilities/pendingSuperiorityDie.mjs';
import {maneuversGoadingAttack as goadingAttackLegacy} from '../../../../2014/classFeatures/fighter/battleMaster/maneuvers.js';

// CPR's 23 maneuvers are registered ONLY in the legacy registry, and premade lookup picks the pack
// by the item's ruleset (`integrations/ddbi.js` maps 2014 -> legacy, 2024 -> modern), so a 2024-rules
// Battle Master could never match any of them. These are the first three ported forward, chosen
// because they are the ones actually on the table.

// 2024 PHB, Riposte: "When a creature misses you with a melee attack roll, you can take a Reaction
// and expend one Superiority Die to make a melee attack roll with a weapon or an Unarmed Strike
// against the creature. If you hit, add the Superiority Die to the attack's damage."
//
// ⚠️ Upstream binds `maneuversRiposte` to `useBrace` (2014 maneuvers.js:597) — Brace's handler. The
// two are mechanically near-identical, so it works by accident rather than being broken, but it is a
// maintenance trap: tuning Brace silently retunes Riposte. The modern entry gets its own handler,
// which also adds the Unarmed Strike option 2024 introduced. Legacy stays weapon-only on purpose —
// 2014 Riposte reads "melee weapon attack".
async function useRiposte({workflow}) {
    if (workflow.targets.size !== 1) return;
    let attacks = workflow.token.actor.items.filter(i => {
        if (constants.unarmedAttacks.includes(genericUtils.getIdentifier(i))) return true;
        return i.type === 'weapon' && i.system.equipped && i.system.activities.getByType('attack').some(j => j.actionType === 'mwak');
    });
    if (!attacks.length) return;
    let [itemToUse, superiorityDie] = await determineSuperiorityDie(workflow.actor);
    if (!itemToUse?.system.uses.value) return;
    let selected;
    if (attacks.length === 1) {
        selected = attacks[0];
    } else {
        selected = await dialogUtils.selectDocumentDialog(workflow.item.name, 'CHRISPREMADES.Macros.Antagonize.SelectWeapon', attacks);
    }
    if (!selected) return;
    /**
     * ⚠️ ALL THREE OPTIONS ARE LOAD-BEARING.
     *
     * `maneuverAttack` — marks this as an attack GENERATED BY a maneuver, so the superiority driver
     * does not offer a second maneuver on it. RAW, "You can use only one maneuver per attack" (2024
     * Combat Superiority, verbatim); Riposte is itself the maneuver on this attack.
     *
     * `notReaction` — ⚠️ WITHOUT THIS THE PLAYER IS ASKED TO SPEND THEIR REACTION TWICE.
     * With midi's `recordAOO` on (this world runs "all"), midi flags ANY in-combat attack made
     * outside the actor's own turn as an opportunity attack: `workflow.AoO = true` and
     * `itemUsesReaction = true`. A Riposte counter-attack is by definition out-of-turn, so midi tries
     * to consume a reaction that the Riposte item itself has ALREADY consumed — surfacing as
     * "You have used your reaction this round. Do you want to proceed anyway?" between the weapon
     * choice and the attack. `notReaction` skips that whole reaction/AoO block.
     * Established in T3 — see [[midiqol-invocation-and-autoroll]]; the same heuristic is why an
     * out-of-turn attack also skips midi's out-of-range abort.
     *
     * `chris-premades.superiorityDie` — the die this Riposte spends, added to the counter-attack's
     * damage by `appendSuperiorityDie` below. ⚠️ This used to be an ActiveEffect on
     * `system.bonuses.mwak.damage`; that shape is a RULES BUG (T93) — see that handler for why.
     * The namespaced sub-object is the house pattern for passing our own data through a synthetic
     * roll (cf. `squaredCircle/cleanFinish.js`); midi merges `options.workflowOptions` onto the new
     * workflow verbatim (`Workflow.ts`), which is the same channel the two flags above ride.
     */
    await workflowUtils.syntheticItemRoll(selected, [workflow.targets.first()], {
        options: {
            workflowOptions: {
                maneuverAttack: true,
                notReaction: true,
                'chris-premades': {superiorityDie}
            }
        }
    });

    /**
     * ⚠️ DO NOT UNCONDITIONALLY SPEND HERE — THAT IS A DOUBLE SPEND.
     *
     * The activity carries an `itemUses` consumption target pointing at the actor's Superiority
     * Dice item (re-pointed at add-time by `added`, see T83), so using Riposte ALREADY spends one
     * die. `determineSuperiorityDie` returns that same item for an ordinary Battle Master, so
     * decrementing again costs two dice per Riposte.
     *
     * It read as correct for a long time only because the consumption target was an unresolvable
     * compendium placeholder — dnd5e silently spent nothing and this line was the sole spend.
     * Repairing the target (T83) armed the second one. Upstream's legacy entry has the same shape.
     *
     * The manual decrement still has one real job: `determineSuperiorityDie` may pick a DIFFERENT
     * pool (Martial Adept, Superior Technique fighting style), which the activity's fixed target
     * cannot express. Spend by hand only in that case.
     */
    let consumedTarget = workflow.activity?.consumption?.targets?.find(i => i.type === 'itemUses')?.target;
    if (consumedTarget !== itemToUse.id) {
        await genericUtils.update(itemToUse, {'system.uses.spent': itemToUse.system.uses.spent + 1});
    }
}

/**
 * Add the spent Superiority Die to the Riposte counter-attack's damage roll.
 *
 * ⚠️ WHY NOT AN ACTIVE EFFECT ON `system.bonuses.mwak.damage` — WHICH IS WHAT THIS USED TO DO:
 * dnd5e's `_processDamagePart` pushes that global bonus into damage part **index 0 only**, and
 * `BasicRoll.fromConfig` then flattens the parts with `parts.join(' + ')`. The die therefore ends
 * up as an ordinary term of `workflow.damageRolls[0]` with NO surviving provenance — nothing in
 * the finished roll can tell it apart from the weapon's own dice.
 *
 * That is what broke Savage Attacker: its damage pass re-evaluates `workflow.damageRolls[i]` for
 * every `i < activity.damage.parts.length`, so it rerolled the superiority die together with the
 * weapon's dice (observed at the table 2026-07-27, T93). RAW the feat rerolls "the **weapon's**
 * damage dice"; a superiority die is granted by the maneuver and merely ADDED to the attack's
 * damage roll, so it is not one of them. Savage Attacker firing on a Riposte at all is correct —
 * only its reach was wrong.
 *
 * `bonusDamage` APPENDS a separate roll at index >= `damage.parts.length`, i.e. outside that
 * window. This is why every driver-invoked maneuver was already correct (`superiorityHelper` has
 * always used it), and it is also the shape RAW describes: "Add the Superiority Die to the
 * attack's damage roll."
 *
 * ⚠️ PRIORITY 50 IS LOAD-BEARING. CPR sorts passes ASCENDING (`events/midi.js`:
 * `sort((a, b) => a.priority - b.priority)`), so a lower number runs first. This must stay above
 * Savage Attacker's `damageRollComplete` pass (25) so the die is appended after it has chosen.
 *
 * No packData change is needed to reach an already-deployed item: the flag lists macro NAMES
 * (`macros.midi.actor: ['maneuversRiposte']`), and `collectActorMacros` filters this registry
 * entry by pass at runtime — so a new actor pass is picked up automatically. Contrast the T83
 * landmine, which bites when an item declares no `midi.actor` entry at all.
 */
async function appendSuperiorityDie({trigger: {entity: item}, workflow}) {
    let superiorityDie = workflow.workflowOptions?.['chris-premades']?.superiorityDie;
    if (!superiorityDie) return;
    await workflowUtils.bonusDamage(workflow, superiorityDie, {damageType: workflow.defaultDamageType});
    // Explain the extra die on the card's damage ⓘ — otherwise it reads as a mystery die, which
    // is doubly confusing next to a Savage Attacker reroll note that deliberately did NOT touch it.
    await rollUtils.postRerollNote(workflow, {
        source: item.name,
        kind: 'superiorityDie',
        die: superiorityDie,
        total: workflow.damageRolls.at(-1).total
    });
}

/**
 * Offer Riposte automatically when a creature MISSES this actor with a melee attack roll.
 *
 * WHY A TARGET-SIDE PASS: Riposte was registered only on `midi.item` / `rollFinished`, which fires
 * on the holder's OWN use — so nothing watched attacks made *against* them and the reaction had to
 * be invoked by hand. This mirrors what upstream already does for **Parry**, which reacts from
 * `midi.actor` / `targetApplyDamage`; the two differ only in trigger (miss vs damage), which is why
 * the gate below is shared rather than the whole handler.
 *
 * RAW (2024 PHB, verbatim): "When a creature misses you with a melee attack roll, you can take a
 * Reaction and expend one Superiority Die to make a melee attack roll…". Note **melee attack roll**,
 * not melee *weapon* attack — a melee spell attack qualifies, which `isAttackType(…, 'meleeAttack')`
 * already covers.
 */
async function offerRiposte({trigger, workflow}) {
    let item = trigger.entity;
    // The miss is the whole trigger: this pass runs for every target, hit or not.
    if (workflow.hitTargets?.has(trigger.token)) return;
    if (!await canReactWithManeuver(item, workflow)) return;
    if (!await dialogUtils.confirmUseItem(item, {userId: socketUtils.firstOwner(item.parent, true)})) return;
    // Target the attacker — `useRiposte` reads `workflow.targets` to pick who to strike back at.
    // `consumeResources` so the activity's own consumption spends the die exactly once.
    await workflowUtils.syntheticItemRoll(item, [workflow.token], {consumeResources: true});
}

const PARRY_FLAG = 'parryReduction';

/**
 * Remember what a Parry rolled, so the attacker's workflow can subtract it.
 *
 * ⚠️ **WE DO NOT OFFER PARRY OURSELVES, AND THAT IS DELIBERATE.** midi already does: its
 * ReactionDialog lists the item, and `utils.ts:5508` defaults an unconditioned reaction to
 * `reaction === "isHit"`. The packData narrows that to `isDamaged`, which is the trigger 2024
 * actually names ("When another creature DAMAGES you with a melee attack roll") and the point at
 * which the total is known. Adding a CPR prompt on top would mean two dialogs for one reaction.
 *
 * The roll and the damage live in DIFFERENT workflows — Parry's own use produces the number, the
 * attacker's workflow owns the damage item — so the number is stashed here and consumed by
 * `applyParryReduction` at `targetApplyDamage`. midi fires the `isDamaged` reaction inside
 * `processDamageRoll`, and `preTargetDamageApplication` (which is what `targetApplyDamage` rides)
 * runs after it, so the stash is always in place before the consumer looks.
 *
 * ⚠️ **THE ACTIVITY'S OWN ROLL IS THE NUMBER — do not roll again here.** A utility activity whose
 * `roll.visible` is false rolls its formula automatically, so `workflow.utilityRoll` is already
 * populated. Rolling a second time in code (as the legacy handler does, because its activity ships an
 * empty formula) posts TWO identical cards for one parry — observed live before this was corrected.
 *
 * ⚠️ Consequence worth knowing: the formula reads `@scale.battle-master.combat-superiority-die`, so
 * an alternate pool — Martial Adept or the Superior Technique fighting style, both flat d6 — rolls
 * the Battle Master die instead. Every other 2024 maneuver that reads the scale key has the same
 * limitation (Feinting, Lunging); fixing it belongs to all of them at once, not here.
 */
async function stashParryReduction({trigger: {entity: item}, workflow}) {
    let reduction = workflow.utilityRoll?.total;
    if (!reduction) return;
    await genericUtils.setFlag(item.parent, 'chris-premades', PARRY_FLAG, reduction);
}

/**
 * Subtract a parried amount from the damage about to be applied.
 *
 * `targetApplyDamage` is the last pass where `ditem` is still mutable, which is what "reduce the
 * damage" needs. `modifyDamageAppliedFlat` clamps at `-hpDamage - tempDamage`, so an oversized roll
 * can never turn into accidental healing.
 *
 * ⚠️ The stash is cleared unconditionally once read. Leaving it would quietly reduce the NEXT attack
 * as well, which is the sort of thing that looks like a defence bonus nobody can account for.
 */
async function applyParryReduction({trigger: {entity: item}, workflow, ditem}) {
    let reduction = item.parent?.flags['chris-premades']?.[PARRY_FLAG];
    if (!reduction) return;
    await genericUtils.setFlag(item.parent, 'chris-premades', PARRY_FLAG, null);
    if (!ditem.isHit) return;
    if (!workflowUtils.isAttackType(workflow, 'meleeAttack')) return;
    workflowUtils.modifyDamageAppliedFlat(ditem, -reduction);
}

/**
 * The shared gate for a REACTION maneuver offered from the target side (Riposte's own offer).
 * Deliberately does NOT check hit/miss — that is the per-maneuver trigger.
 * ⚠️ Parry does NOT use this: midi offers Parry, so CPR only applies the result.
 * @returns {Promise<boolean>}
 */
async function canReactWithManeuver(item, workflow) {
    if (!workflowUtils.isAttackType(workflow, 'meleeAttack')) return false;
    let [itemToUse] = await determineSuperiorityDie(item.parent);
    if (!itemToUse?.system.uses.value) return false;
    if (actorUtils.hasUsedReaction(item.parent)) return false;
    return true;
}

// A creature's name as the ASKED CHARACTER would know it, not as the GM does.
//
// ⚠️ The prompt is composed GM-side and socketed to whoever answers it, so the veil module's own
// `effectiveViewer()` is the wrong frame — on a GM client it returns `{omniscient: true}` and a
// veiled NPC's true name goes straight into the dialog text. Framing it on the ALLY token asks the
// question that actually matters ("can the character being asked tell who that is?") and gives the
// same answer no matter which user reads the dialog.
//
// `{omniscient: false, refs: [token]}` is the module's own supported viewer shape — it is exactly
// what `computeEffectiveViewer` builds for a GM with a PC selected. A no-op for PCs, and for NPCs
// when the module is disabled or the creature is already identified.
// ⚠️ The effect description bakes this in at creation time, so a name resolved as a placeholder
// stays a placeholder even if the ally later closes the distance. Acceptable as a snapshot.
function veiledName(token, viewerToken) {
    let veil = game.modules.get('npc-name-veil')?.api;
    if (!veil?.getDisplayName) return token.name;
    return veil.getDisplayName(token, {omniscient: false, refs: [viewerToken]});
}

// Ally selection, on canvas where possible. Argon's own picker is what the player already uses to
// choose an attack target, so picking the ally the same way is one less modality — but it only
// exists while the HUD is running, and a sheet click has no picker at all (that gap is T79). The
// dialog list stays as the fallback so the sheet path is never dead.
async function pickAlly(workflow, candidates) {
    let picker = game.modules.get('enhancedcombathud')?.active ? game.modules.get('enhancedcombathud').api?.runTargetPicker : null;
    if (picker) {
        // ⚠️ runTargetPicker resolves to a BOOLEAN (true = completed, false = cancelled), NOT to the
        // tokens picked — the selection is left in `game.user.targets`. Assuming it returned tokens
        // made this whole branch a silent no-op: `Array.from(true)` is `[]`, so no ally was ever
        // chosen, no confirmation was ever raised, and no exemption was ever applied. It failed
        // without an error, which is why it looked like it worked.
        let completed = await picker({
            token: workflow.token,
            targets: 1,
            label: genericUtils.translate('CHRISPREMADES.Macros.Maneuvers.SelectAlly'),
            item: workflow.item
        });
        if (!completed) return undefined;
        let chosen = Array.from(game.user.targets)[0];
        if (!chosen) return undefined;
        // The picker targets any token — deliberately, since RAW leaves the choice to the player and
        // Vittorio asked to trust them. Warn on a pick outside the see-or-hear ally set rather than
        // refusing it, so an unusual-but-legal choice still goes through.
        if (!candidates.some(c => c.id === chosen.id)) {
            genericUtils.notify('CHRISPREMADES.Macros.Maneuvers.NotAnAlly', 'warn');
        }
        return chosen;
    }
    let picked = await dialogUtils.selectTargetDialog(workflow.item.name, 'CHRISPREMADES.Macros.Maneuvers.SelectAlly', candidates);
    return picked?.[0];
}

// 2024 PHB, Maneuvering Attack: "...choose a willing creature who can see or hear you. That creature
// can use its Reaction to move up to half its Speed without provoking Opportunity Attacks from the
// target of your attack."
//
// Two changes from the legacy handler:
//   1. "see OR hear" — legacy checked sight only (`tokenUtils.canSee`). `canSense(..., ['all'])`
//      matches on any detection mode the world defines, which with vision-5e installed includes its
//      `hearing` mode; with vision-5e absent it still covers sight, i.e. never worse than legacy.
//   2. The OA exemption is now real. The chosen ally gets `flags.midi-qol.oaManeuveringAttack`
//      carrying the attacked creature's token id, which our GPS fork's opportunityAttack.js skips on
//      — the same per-pair mechanism upstream GPS already uses for the Mobile feat and Fancy
//      Footwork. Written as an ActiveEffect CHANGE, not a stored flag, so removing the effect removes
//      the exemption; nothing has to remember to clean up.
//
// ⚠️ "The target of your attack" is read from the workflow BEFORE the ally retarget below, i.e. it is
// whoever Xender still has targeted when he uses the maneuver — true in the normal flow (attack, then
// use the maneuver), but it is an inference, not something the item records. With no target held, the
// ally is still designated and still spends its Reaction; only the OA exemption is skipped.
async function useManeuveringAttack({workflow}) {
    let attackedToken = workflow.targets.first();
    let candidates = workflow.token.scene.tokens.filter(t => {
        if (!t.actor) return false;
        if (t.id === workflow.token.id) return false;
        if (t.disposition !== workflow.token.document.disposition) return false;
        return tokenUtils.canSense(t.object, workflow.token, ['all']);
    }).map(t => t.object);
    if (!candidates.length) {
        await workflowUtils.updateTargets(workflow, []);
        return;
    }
    let ally = await pickAlly(workflow, candidates);
    if (!ally) {
        await workflowUtils.updateTargets(workflow, []);
        return;
    }
    // The prompt is often read by someone holding several characters at once — the GM covering absent
    // players, most of all — so it has to say WHO is being asked and WHY, not just "spend your
    // reaction?". Title carries the ally's token name, mirroring the Alert feat's `Alert — {name}`
    // ([[dnd5e-alert-initiative-swap]]); the body restates the whole situation, since the ally may not
    // have been watching the attack that triggered it.
    // ⚠️ Names are token names (falling back to actor names), which is what the players see on the
    // board. A veiled NPC's true name would surface here — acceptable, since the ally is being told
    // about a creature that just attacked in front of them, but it is the one leak worth knowing about.
    let names = {
        name: ally.name ?? ally.actor.name,
        attacker: veiledName(workflow.token, ally),
        enemy: attackedToken ? veiledName(attackedToken, ally) : game.i18n.localize('DND5E.Target')
    };
    dialogUtils.confirm(
        genericUtils.format('CHRISPREMADES.Macros.Maneuvers.ManeuveringTitle', names),
        genericUtils.format('CHRISPREMADES.Macros.Maneuvers.ManeuveringPrompt', names),
        {userId: socketUtils.firstOwner(ally.actor, true)}
    ).then(async choice => {
        if (!choice) return;
        actorUtils.setReactionUsed(ally.actor);
        if (!attackedToken || attackedToken.id === ally.id) return;
        await effectUtils.createEffect(ally.actor, {
            name: workflow.item.name,
            img: workflow.item.img,
            origin: workflow.item.uuid,
            // Without an explicit description Visual Active Effects falls back to the origin item's,
            // i.e. the entire feature text. The ally does not need the rules quotation — they need
            // what they may do right now, and against whom.
            description: genericUtils.format('CHRISPREMADES.Macros.Maneuvers.ManeuveringEffect', names),
            duration: {
                rounds: 1
            },
            changes: [
                {
                    key: 'flags.midi-qol.oaManeuveringAttack',
                    mode: 2,
                    value: attackedToken.id,
                    priority: 20
                }
            ],
            flags: {
                dae: {
                    specialDuration: [
                        'turnEndSource'
                    ]
                }
            }
        });
    });
    await workflowUtils.updateTargets(workflow, [ally]);
}

// ⚠️ WITHOUT THIS, A DIRECTLY-USED MANEUVER CANNOT BE SPENT AT ALL (T83, 2026-07-27).
//
// The packData ships its consumption target as a COMPENDIUM UUID placeholder
// (`Compendium.chris-premades.CPRClassFeatures.Item.tr7yGwS1sVVeJVXt`), which is meaningless once
// the item sits on an actor — dnd5e cannot resolve it to anything the character owns, so the
// consumption prompt reports "0 of 1 usage" while Combat Superiority sits there at 4/4. Upstream
// fixes this at add-time by re-pointing the target to the actor's OWN Superiority Dice item, and
// the T56 slice ported the maneuvers without porting that step.
//
// Only maneuvers that carry an item-level consumption target need this, and that is a real
// distinction rather than an oversight: the ON-HIT riders (Goading Attack, Maneuvering Attack, …)
// are spent by the `superiorityDice` DRIVER, which decrements the die itself
// (`2014/.../superiorityDice.js:74`), so they deliberately have no target. Riposte is a Reaction
// used directly from the sheet, so nothing else would ever spend its die.
//
// ⚠️ Do NOT register this on a maneuver with no consumption target — `correctActivityItemConsumption`
// writes `consumption.targets[0].target` unconditionally and would throw on an empty array.
async function added({trigger: {entity: item}}) {
    await itemUtils.correctActivityItemConsumption(item, ['use'], 'superiorityDice');
}

export let maneuversRiposte = {
    name: 'Maneuvers: Riposte',
    // No bare-name alias on purpose: the Monster Manual ships an NPC feat also called "Riposte"
    // (dnd5e.monsterfeatures24 / dnd-monster-manual.features `mmRiposte0000000`), and a bare alias
    // would put this Battle Master automation in front of it. `Maneuver: X` is what our DDB fork's
    // enricher produces, which is what a real 2024 sheet actually carries.
    aliases: ['Maneuver: Riposte'],
    // 1.0.3 — the counter-attack no longer re-asks for a reaction (notReaction, see useRiposte).
    // 1.0.4 — the superiority die is APPENDED as bonus damage instead of being folded into the
    //         weapon's own damage part, so Savage Attacker stops rerolling it (T93).
    // 1.0.5 — ⚠️ BUGFIX: midi was ALSO offering Riposte, on a HIT. It ships no reaction condition, so
    //         it inherited midi's `isHit` default (utils.ts:5508) — but 2024 Riposte triggers on a
    //         MISS. Every hit therefore offered a Riposte the character was not entitled to. The
    //         packData now sets `useConditionText: 'false'` to suppress midi's generic offer;
    //         `offerRiposte` below is already correctly miss-gated, so re-pointing midi at isMissed
    //         instead would merely have produced two prompts for the same legitimate trigger.
    // ⚠️ The version here is the MACRO registry stamp; `isUpToDate` reads it while the packData
    // carries its own. Bump BOTH or an already-deployed item never reports out-of-date.
    version: '1.0.5',
    rules: 'modern',
    // Three passes, matching upstream's legacy registration: `created` covers a fresh add,
    // `itemMedkit` an item-level Medkit run, `actorMunch` a DDB (re-)import. An item already on a
    // sheet before this shipped is only repaired by one of the latter two — see the memory note.
    item: [
        {
            pass: 'created',
            macro: added,
            priority: 55
        },
        {
            pass: 'itemMedkit',
            macro: added,
            priority: 55
        },
        {
            pass: 'actorMunch',
            macro: added,
            priority: 55
        }
    ],
    midi: {
        item: [
            {
                pass: 'rollFinished',
                macro: useRiposte,
                priority: 50
            }
        ],
        // Target-side: fires on THIS actor when someone attacks them, so the reaction is offered
        // without the player having to remember it. `targetAttackRollComplete` is the first pass
        // where hit/miss is known, which is exactly Riposte's trigger.
        actor: [
            {
                pass: 'targetAttackRollComplete',
                macro: offerRiposte,
                priority: 50
            },
            // Self-side: fires on the counter-attack's own damage roll. Gated on the workflow
            // option `useRiposte` sets, so it is inert on every other attack this actor makes.
            {
                pass: 'damageRollComplete',
                macro: appendSuperiorityDie,
                priority: 50
            }
        ]
    }
};
export let maneuversGoadingAttack = {
    name: 'Maneuvers: Goading Attack',
    aliases: ['Maneuver: Goading Attack'],
    version: '1.0.0',
    rules: 'modern',
    // Edition-stable: the 2014 and 2024 wordings are identical (Wisdom save, Disadvantage on attacks
    // against anyone but you, until the end of your next turn), so the legacy handler ports verbatim.
    // Worth knowing: this is the only source that implements the Disadvantage at all — the official
    // PHB 2024 item and our DDB enricher both ship a `Goaded` effect with ZERO changes, i.e. a marker.
    midi: {
        item: [
            {
                pass: 'rollFinished',
                macro: goadingAttackLegacy.midi.item[0].macro,
                priority: 50
            }
        ]
    }
};
export let maneuversManeuveringAttack = {
    name: 'Maneuvers: Maneuvering Attack',
    aliases: ['Maneuver: Maneuvering Attack'],
    version: '1.0.0',
    rules: 'modern',
    midi: {
        item: [
            {
                pass: 'preambleComplete',
                macro: useManeuveringAttack,
                priority: 50
            }
        ]
    }
};

/*
 * T81 BATCH A — the seven maneuvers that need no macro at all.
 *
 * Their whole automation lives in the item encoding (a midi `optional` bonus effect, or a save
 * activity), so porting them forward is a modern registration plus a `cpr-class-features-2024`
 * packData entry and nothing else. The driver below is still what invokes the on-hit ones.
 *
 * ⚠️ Only Evasive Footwork carries an item-level `consumption.targets`, so it is the ONLY one of the
 * seven that gets the `added` repair passes — `correctActivityItemConsumption` writes
 * `consumption.targets[0].target` unconditionally and would THROW on the empty array the other six
 * have. The split is the §T83 distinction: an on-hit rider's die is spent by the driver, a directly
 * used maneuver spends its own.
 *
 * ⚠️ Descriptions on the packData entries are the official 2024 PHB text
 * (`dnd-players-handbook.classes`, `system.type.subtype === 'maneuver'`), read live rather than
 * hand-copied. Three of the seven diverge from the 2014 encoding in ways a macro-free entry cannot
 * express — see the notes on Ambush, Evasive Footwork and Precision Attack below. Those are
 * deliberately left as Batch B work rather than guessed at here.
 */

export let maneuversAmbush = {
    name: 'Maneuvers: Ambush',
    // Upstream's legacy entry declares NO alias, which would have made this port unreachable: our
    // DDB fork's enricher produces `Maneuver: Ambush`, and that is what a real 2024 sheet carries.
    aliases: ['Maneuver: Ambush'],
    version: '1.0.0',
    rules: 'modern',
    // ⚠️ 2024 RAW is "a Dexterity (Stealth) check OR AN INITIATIVE ROLL"; the encoding implements
    // only the Stealth half (`flags.midi-qol.optional.Ambush.skill.ste`). That gap is upstream's and
    // exists identically in the legacy entry — it is NOT something this port introduced, and closing
    // it needs a mechanism midi's `optional` vocabulary does not offer for initiative. Batch B.
};
export let maneuversCommandingPresence = {
    name: 'Maneuvers: Commanding Presence',
    aliases: ['Maneuver: Commanding Presence'],
    version: '1.0.0',
    rules: 'modern'
    // Edition-stable: 2014 and 2024 both cover Intimidation, Performance and Persuasion, which is
    // exactly what the effect grants (`skill.itm` / `skill.prf` / `skill.per`).
    // ⚠️ The legacy packData entry's `info.name` reads "Maneuvers: Ambush" — an upstream copy-paste.
    // Corrected on the 2024 entry.
};
export let maneuversDisarmingAttack = {
    name: 'Maneuvers: Disarming Attack',
    aliases: ['Maneuver: Disarming Attack'],
    version: '1.0.0',
    rules: 'modern'
    // 2024 only sharpens the wording ("one object of your choice that it's holding, with the object
    // landing in its space"); the mechanic — a Strength save or drop it — is unchanged.
};
export let maneuversEvasiveFootwork = {
    name: 'Maneuvers: Evasive Footwork',
    aliases: ['Maneuver: Evasive Footwork'],
    // 1.0.1 — ⚠️ BUGFIX (found 2026-07-29 while building slice 2's Feinting Attack off this shape).
    // This registers the `added` consumption re-pointer below, but its packData carried NO
    // `flags.chris-premades.activityIdentifiers`, and that map is the ONLY thing
    // `activityUtils.getActivityByIdentifier` reads. So `correctActivityItemConsumption(item,
    // ['use'], …)` resolved nothing on every add, with two visible consequences: a warning toast
    // ("Activity not found") via the `strict: true` path, and — the real damage — the consumption
    // target left pointing at the COMPENDIUM Superiority Dice item, which is exactly the "0 of 1
    // usage while Combat Superiority sits at 4/4" failure the re-pointer exists to prevent.
    // Fixed by adding `activityIdentifiers: {use: 'dnd5eactivity000'}` to the packData entry.
    // 1.1.0 — the DISENGAGE half now ships too (slice 5). See below.
    // 1.1.1 — ⚠️ BUGFIX: same as Rally's 1.0.1 — the `added` passes were registered but never
    //         declared in packData, so the §T83 re-pointer had never actually run.
    version: '1.1.1',
    rules: 'modern',
    // ✅ 2024 DIFF NOW FULLY PORTED. 2014: "When you move… add the die to your AC until you stop
    // moving." 2024: "AS A BONUS ACTION… and TAKE THE DISENGAGE ACTION. You also… add the number
    // rolled to your AC UNTIL THE START OF YOUR NEXT TURN."
    //
    // ⚠️ The Disengage half needed NO handler — Batch A assumed it would, which is why it was
    // deferred. It is a SECOND EFFECT granting `flags.gambits-premades.oaImmunity`, the flag our GPS
    // fork reads in `opportunityAttack.js` to suppress the offer against the moving token. Modelled
    // on CPR's own Disengage action so the two are interchangeable, and named "Disengage" with DAE
    // `noneName` so taking the real action as well cannot stack two markers.
    //
    // ⚠️ IT CANNOT BE FOLDED INTO THE AC EFFECT — the two halves expire at different moments.
    // The AC bonus runs to `turnStartSource` ("until the start of your next turn"); Disengage only
    // to `turnEnd` ("for the rest of the turn"). Sharing one effect would leave you immune to
    // opportunity attacks through every other creature's turn — and you CAN be moved in that window
    // by a reaction, which is precisely what Maneuvering Attack grants an ally.
    //
    // ⚠️ Contrast Lunging Attack's Dash, deliberately NOT automated in slice 3: CPR models Dash as
    // pure animation with zero mechanical changes, so wiring it would have added nothing and made
    // the maneuver un-verifiable headless. Disengage is the opposite — it carries a real flag.
    //
    // The only Batch A maneuver with its own `consumption.targets`, hence the §T83 repair passes:
    // CPR ships the target as a compendium UUID placeholder that dnd5e cannot resolve on an actor.
    item: [
        {
            pass: 'created',
            macro: added,
            priority: 55
        },
        {
            pass: 'itemMedkit',
            macro: added,
            priority: 55
        },
        {
            pass: 'actorMunch',
            macro: added,
            priority: 55
        }
    ]
};
export let maneuversMenacingAttack = {
    name: 'Maneuvers: Menacing Attack',
    aliases: ['Maneuver: Menacing Attack'],
    version: '1.0.0',
    rules: 'modern'
    // Edition-stable wording. ⚠️ The legacy effect is an inert marker with no `statuses` — the target
    // "must succeed on a Wisdom saving throw or have the Frightened condition", and nothing applied
    // it. The 2024 entry carries `statuses: ['frightened']`, which is the printed rule and needs no
    // macro. (Same shape as the Goaded marker, except Goaded's mechanic lives in a handler.)
};
export let maneuversPrecisionAttack = {
    name: 'Maneuvers: Precision Attack',
    aliases: ['Maneuver: Precision Attack'],
    // 1.1.0 — the 2024 miss-only gate, via midi's own `attack.fail.*` channel. See below.
    version: '1.1.0',
    rules: 'modern',
    // ✅ 2024 DIFF NOW PORTED (Batch B slice 1). 2014 let you add the die "before or after making
    // the attack roll"; 2024 is miss-only — "When you MISS with an attack roll, you can expend one
    // Superiority Die… potentially causing the attack to hit."
    //
    // ⚠️ This needed NO macro and NO midi patch — midi already implements a miss-only optional-bonus
    // channel and we were simply on the wrong one. `Workflow.processAttackRollBonusFlags` runs two
    // passes: `optional.<flag>.attack.<actionType>` on EVERY attack, then — gated on `isMiss`,
    // computed against the AC captured at roll time — `optional.<flag>.attack.fail.<actionType>`.
    // So the whole 2024 gate is the packData effect keys moving from `.attack.mwak/rwak` to
    // `.attack.fail.mwak/rwak`. This item stays macro-free.
    //
    // Re-resolution is midi's too: `AttackActivity.rollAttack` calls `processAttackRollBonusFlags()`
    // and only afterwards does `WorkflowState_AttackRollComplete` run `checkHits()`, so a die added
    // through the fail channel is on the roll before hits are decided. Nothing re-runs by hand.
    //
    // ⚠️ KNOWN LIMIT, upstream: midi guards the fail pass with `if (this.targets.size === 1)`, so on
    // a multi-target attack the offer never appears. Single-target is the norm for Precision Attack,
    // and widening it would be a midi source-fork change for a rare case — deliberately not taken.
    //
    // ⚠️ The offer appearing IS the information "you missed" — which is correct here rather than a
    // leak, because 2024's trigger is literally the miss (Vittorio, 2026-07-29). Contrast T2/T86.
};
/**
 * 2024 Pushing Attack's push: "If the target is Large or smaller, it must succeed on a Strength
 * saving throw or be pushed up to 15 feet directly away from you."
 *
 * The official PHB item stops at the save — it rolls the die and offers the throw but never moves
 * anybody — so this is the half that has to be ours. "Up to 15 feet" is a genuine choice (shoving a
 * target the full distance can push it out of your reach, or into cover), so it prompts, exactly as
 * the 2014 handler did.
 *
 * ⚠️ Reads `workflow.failedSaves`, so it must run after saves settle — hence `rollFinished`.
 */
async function pushOnFailedSave({workflow}) {
    if (!workflow.failedSaves?.size) return;
    let buttons = [5, 10, 15].map(i => [genericUtils.format('CHRISPREMADES.Distance.DistanceFeet', {distance: i}), i]);
    let distance = await dialogUtils.buttonDialog(workflow.item.name, 'CHRISPREMADES.Macros.Maneuvers.PushDistance', buttons);
    if (!distance) return;
    for (let target of workflow.failedSaves) {
        await tokenUtils.pushToken(workflow.token, target, distance);
    }
}

/**
 * 2024 Lunging Attack: "As a Bonus Action, you can expend one Superiority Die and take the Dash
 * action. If you move at least 5 feet in a straight line immediately before hitting with a melee
 * attack as part of the Attack action on this turn, you can add the Superiority Die to the attack's
 * damage roll."
 *
 * ⚠️ COMPLETE REWRITE vs 2014, which was simply "increase your reach for that attack by 5 feet" —
 * immediate, self-contained, and nothing like this. Nothing of the legacy handler ports.
 *
 * ⚠️ **The Dash action is deliberately NOT automated**, for two reasons that point the same way.
 * CPR's own `actions/dash.js` grants no movement either — its packData effect carries ZERO changes
 * and the macro is purely a Sequencer animation — so automating it would add no mechanics, only
 * visuals. And that animation routes through CPR's `Crosshairs`, which cannot render in headless
 * Chromium (T72/T91), so wiring it would make this maneuver permanently un-verifiable solo. Taking
 * the Dash is left to the player, exactly as CPR leaves it for the Dash action itself.
 */
async function useLungingAttack({workflow}) {
    let [, superiorityDie] = await determineSuperiorityDie(workflow.actor);
    if (!superiorityDie) return;
    await bankSuperiorityDie(workflow, {
        identifier: 'maneuversLungingAttack',
        die: superiorityDie,
        // No target reservation: 2024 Lunging pays out on ANY qualifying melee hit this turn.
        requiresMelee: true,
        requiresMovement: true
    });
}
export let maneuversLungingAttack = {
    name: 'Maneuvers: Lunging Attack',
    aliases: ['Maneuver: Lunging Attack'],
    // 1.0.1 — ⚠️ BUGFIX: registered the §T83 `added` re-pointer but never declared
    //         `macros.item` in packData, so the passes were never collected and the
    //         consumption target stayed on the compendium placeholder. See Rally 1.0.1.
    version: '1.0.1',
    rules: 'modern',
    midi: {
        item: [
            {
                pass: 'rollFinished',
                macro: useLungingAttack,
                priority: 50
            }
        ]
    },
    item: [
        {
            pass: 'created',
            macro: added,
            priority: 50
        },
        {
            pass: 'itemMedkit',
            macro: added,
            priority: 50
        },
        {
            pass: 'actorMunch',
            macro: added,
            priority: 50
        }
    ]
};
export let maneuversFeintingAttack = {
    name: 'Maneuvers: Feinting Attack',
    aliases: ['Maneuver: Feinting Attack'],
    // 1.0.1 — ⚠️ BUGFIX: registered the §T83 `added` re-pointer but never declared
    //         `macros.item` in packData, so the passes were never collected and the
    //         consumption target stayed on the compendium placeholder. See Rally 1.0.1.
    version: '1.0.1',
    rules: 'modern',
    // ⚠️ REAL 2024 DIFF vs 2014, and the reason this is Batch B rather than Batch A: 2014 Feinting
    // Attack gave advantage on "your next attack roll against that creature THIS TURN" too, but CPR's
    // legacy entry never modelled the deferred die at all. The payout rides the slice-2 tracker.
    //
    // ⚠️ It spends its OWN die (Bonus Action, up front) rather than being spent by the driver, so it
    // needs the `added` consumption re-pointer — the §T83 distinction.
    midi: {
        item: [
            {
                pass: 'rollFinished',
                macro: useFeintingAttack,
                priority: 50
            }
        ]
    },
    item: [
        {
            pass: 'created',
            macro: added,
            priority: 50
        },
        {
            pass: 'itemMedkit',
            macro: added,
            priority: 50
        },
        {
            pass: 'actorMunch',
            macro: added,
            priority: 50
        }
    ]
};
/*
 * T81 BATCH B slice 4 — the ports that ride the official 2024 encoding.
 *
 * ⚠️ Their activities are taken WHOLESALE from `dnd-players-handbook.classes`, because WotC's own
 * items already express the 2024 diffs correctly — including the `max(str, dex)` idiom we derived
 * independently for the save DC. The only transform is the scale key: the PHB items read
 * `@scale.battle-master.superiority.die` (a PHB-built sheet) and CPR items read the DDB parse's
 * `@scale.battle-master.combat-superiority-die`.
 */

export let maneuversParry = {
    name: 'Maneuvers: Parry',
    aliases: ['Maneuver: Parry'],
    // 1.1.0 — the roll now REDUCES damage instead of healing it back, and midi's own reaction offer
    // is narrowed from its `isHit` default to `isDamaged`, the trigger 2024 actually names.
    version: '1.1.0',
    rules: 'modern',
    // ✅ 2024 DIFF, and it is Vittorio's `max()` call landing a THIRD time: the reduction is now
    // "the number you roll plus your Strength OR Dexterity modifier (your choice)". Encoded as a
    // reaction Healing activity, `die + max(@abilities.str.mod, @abilities.dex.mod)` — i.e. damage
    // reduction modelled as retroactive healing, which is what the official item does too.
    //
    // ⚠️ CPR DOES NOT PROMPT FOR PARRY — midi already does, and its dialog is what the table sees.
    // The legacy `promptParry` pass is deliberately NOT ported: it would be a second dialog for one
    // reaction. All CPR contributes is the half midi cannot do — turning the rolled number into
    // damage reduction (stashParryReduction -> applyParryReduction).
    // Parry still stays in CPR rather than moving to the GPS fork despite being reaction-shaped:
    // the T95 carve-out, because the superiority-die pool and the driver are CPR's.
    //
    // ⚠️ It spends its OWN die, so it needs the `added` re-pointer — the trap Batch A's Evasive
    // Footwork fell into. Paired with `activityIdentifiers` in the packData entry.
    midi: {
        // Own use: capture what the reaction rolled.
        item: [
            {
                pass: 'rollFinished',
                macro: stashParryReduction,
                priority: 50
            }
        ],
        // Attacker's workflow: subtract it while `ditem` is still mutable.
        actor: [
            {
                pass: 'targetApplyDamage',
                macro: applyParryReduction,
                priority: 50
            }
        ]
    },
    item: [
        {pass: 'created', macro: added, priority: 50},
        {pass: 'itemMedkit', macro: added, priority: 50},
        {pass: 'actorMunch', macro: added, priority: 50}
    ]
};
export let maneuversRally = {
    name: 'Maneuvers: Rally',
    aliases: ['Maneuver: Rally'],
    // 1.0.1 — ⚠️ BUGFIX: it registered the §T83 `added` re-pointer but its packData never declared
    // `macros.item`, so `events/midi.js` never collected the passes and the re-pointer had NEVER
    // run. Its consumption target therefore stayed on the compendium placeholder — the "0 of 1 usage
    // while Combat Superiority sits at 4/4" failure. Same defect as Evasive Footwork's 1.1.1.
    version: '1.0.1',
    rules: 'modern',
    // ✅ REAL 2024 DIFF, expressed statically: temp HP is now "the Superiority Die roll plus half
    // your Fighter level (round down)" — `die + (floor(@classes.fighter.levels/2))`. 2014 added the
    // CHARISMA modifier instead, so porting the legacy encoding verbatim would have been wrong for
    // every Fighter whose Charisma is not half their level.
    //
    // ⚠️ Spends its own die (Bonus Action), so it needs the `added` re-pointer too.
    item: [
        {pass: 'created', macro: added, priority: 50},
        {pass: 'itemMedkit', macro: added, priority: 50},
        {pass: 'actorMunch', macro: added, priority: 50}
    ]
};
export let maneuversTripAttack = {
    name: 'Maneuvers: Trip Attack',
    aliases: ['Maneuver: Trip Attack'],
    version: '1.0.0',
    rules: 'modern',
    // Macro-free: a save activity carrying the die as damage plus a `Tripped` effect whose
    // `statuses: ['prone']` applies the condition on a failed save. The driver appends the die.
    // ⚠️ The "Large or smaller" size gate is NOT enforced — a save activity cannot express it, and
    // the official PHB item does not either. 2014 CPR gated it in a handler, so this is a deliberate
    // permissive step in the same direction as leaving "immediately before" to the GM.
};
export let maneuversPushingAttack = {
    name: 'Maneuvers: Pushing Attack',
    aliases: ['Maneuver: Pushing Attack'],
    version: '1.0.0',
    rules: 'modern',
    // ⚠️ The ONE of the four that cannot be macro-free: the official item ships the save and the
    // damage but never moves anybody, so a macro-free port would be a Pushing Attack that does not
    // push. This pass reads the settled save and shoves the failures.
    // ⚠️ Same unenforced size gate as Trip Attack, for the same reason.
    midi: {
        item: [
            {
                pass: 'rollFinished',
                macro: pushOnFailedSave,
                priority: 50
            }
        ]
    }
};
export let maneuversTacticalAssessment = {
    name: 'Maneuvers: Tactical Assessment',
    aliases: ['Maneuver: Tactical Assessment'],
    version: '1.0.0',
    rules: 'modern'
    // Edition-stable: History, Investigation and Insight in both, matching `skill.his` / `skill.inv`
    // / `skill.ins`.
};

/*
 * T81 BATCH B slice 4b — the two ports that need a HANDLER rather than an encoding.
 *
 * Both are shape-stable between editions (2024 text read from `dnd-players-handbook.classes`), so
 * unlike slice 4a there is no RAW diff to express. What keeps them out of Batch A is that the
 * official items automate nothing interesting: Distracting Strike ships a `Distracted` marker with
 * ZERO changes and says so in its own Foundry Note, and Sweeping Attack ships only a Damage
 * activity — it never rolls the second attack at all. CPR's legacy handlers do model both.
 *
 * ⚠️ Two upstream defects are fixed rather than ported; see `useSweepingAttack`.
 */

/**
 * 2024 Distracting Strike: "When you hit a creature with an attack roll, you can expend one
 * Superiority Die to distract the target. Add the Superiority Die roll to the attack's damage roll.
 * The next attack roll against the target by an attacker other than you has Advantage if the attack
 * is made before the start of your next turn."
 *
 * The die is the driver's business (`superiorityHelper` appends it); this handler only plants the
 * marker.
 *
 * ⚠️ THE EXCLUSION READS `targetActorUuid`, AND THAT IS NOT A TYPO. For a `grants.*` flag midi
 * INVERTS the condition frame: `RollModifierTracker.ts` builds the data with `actor: grantsActor`
 * (the defender, who holds the flag) and `target: tokenForActor(actor)` (the ATTACKER). So inside
 * this condition `targetActorUuid` is the attacker's actor — which is exactly what RAW's "by an
 * attacker other than you" needs to test. Verified against midi 13.0.63.
 */
async function useDistractingStrike({workflow}) {
    if (workflow.targets.size !== 1) return;
    let targetActor = workflow.targets.first()?.actor;
    if (!targetActor) return;
    let effectData = {
        name: workflow.item.name,
        img: workflow.item.img,
        origin: workflow.item.uuid,
        duration: {
            rounds: 1
        },
        changes: [
            {
                key: 'flags.midi-qol.grants.advantage.attack.all',
                mode: 0,
                value: 'targetActorUuid !== "' + workflow.actor.uuid + '"',
                priority: 20
            }
        ],
        flags: {
            dae: {
                // "before the start of your next turn" — the SOURCE's turn, not the target's.
                specialDuration: [
                    'turnStartSource'
                ]
            }
        }
    };
    effectUtils.addMacro(effectData, 'midi.actor', ['distractingStrikeEffect']);
    /**
     * ⚠️ `rules` IS LOAD-BEARING, AND ITS ABSENCE FAILS SILENTLY.
     *
     * `genericUtils.getRules(entity)` infers the ruleset from `system.source.rules` only for ITEMS;
     * for an ActiveEffect it reads `flags.chris-premades.rules` and DEFAULTS TO 'legacy'. The macro
     * above is carried by NAME, and `custom.getMacro(name, rules)` resolves
     * `rules === 'modern' ? macros[name] : legacyMacros[name]`.
     *
     * So an unstamped effect created here would run the 2014 `distractingStrikeEffect` handler. It
     * would even appear to work — the consume-on-first-attack logic is edition-stable — which is
     * what makes it worth pinning: the coupling is invisible until someone tunes the legacy side,
     * the same trap as Riposte silently sharing Brace's handler upstream.
     */
    await effectUtils.createEffect(targetActor, effectData, {rules: distractingStrikeEffect.rules});
}

/**
 * Clear the marker once it has been used: "The NEXT attack roll against the target…".
 *
 * The fighter's own attacks must not consume it — they are the one attacker RAW excludes, so
 * burning it on their follow-up swing would waste a die they already paid.
 *
 * ⚠️ `fromUuid` is guarded where the legacy handler dereferences blind. A marker can outlive its
 * origin item (a DDB re-import deletes and recreates items), and an unguarded throw inside a midi
 * pass takes out the rest of that pass's macros, not just this one.
 */
async function distractingStrikeEffectHit({trigger: {entity: effect}, workflow}) {
    if (!workflow.targets.size) return;
    if (!workflowUtils.isAttackType(workflow, 'attack')) return;
    let originItem = await fromUuid(effect.origin);
    if (originItem?.actor === workflow.actor) return;
    await genericUtils.remove(effect);
}

/**
 * 2024 Sweeping Attack: "When you hit a creature with a melee attack roll using a weapon or an
 * Unarmed Strike, you can expend one Superiority Die to attempt to damage another creature. Choose
 * another creature within 5 feet of the original target and within your reach. If the original
 * attack roll would hit the second creature, it takes damage equal to the number you roll on your
 * Superiority Die. The damage is of the same type dealt by the original attack."
 *
 * The driver stashes the first attack's roll/type/reach on this item
 * (`superiorityHelper`'s `maneuversSweepingAttack` branch) instead of appending the die, because
 * the die belongs to the SECOND creature's damage, not the first's.
 *
 * ⚠️ The superiority die is read straight off the scale rather than via `determineSuperiorityDie`,
 * which would re-prompt for a pool the driver has already picked. `useSmallSuperiorityDie` is the
 * driver's flag for "this use is a d6 pool" (Martial Adept / Superior Technique).
 *
 * ⚠️ TWO UPSTREAM DEFECTS FIXED, NOT PORTED:
 *  1. The legacy gate is `if (!target?.length || !target[1]) return;` — but `selectTargetDialog`
 *     returns `[result, skip]`, where `skip` is the "Skip Dead and Unconscious" CHECKBOX, not a
 *     confirmation. Unchecking it made the whole maneuver a silent no-op with the die already
 *     committed. Cancel is still caught by the first half: the dialog returns `false` on cancel and
 *     `false?.length` is undefined.
 *  2. The two branches returned different types — `target[0].document` (a TokenDocument) from the
 *     dialog, a raw Token from the single-candidate path. Tokens are the house convention here
 *     (cf. `useRiposte`, `useManeuveringAttack`), so both now yield a Token.
 */
async function useSweepingAttack({workflow}) {
    if (!workflow.targets.size) return;
    let superiorityDie = workflow.actor.system.scale?.['battle-master']?.['combat-superiority-die']?.die ?? 'd6';
    let useSmall = genericUtils.getProperty(workflow.actor, 'flags.chris-premades.useSmallSuperiorityDie');
    if (useSmall) superiorityDie = 'd6';
    let {currAttackRoll, currDamageType, currRange} = workflow.item.flags['chris-premades']?.sweepingAttack ?? {};
    if (!currAttackRoll) return;
    let feature = activityUtils.getActivityByIdentifier(workflow.item, 'sweepingAttackAttack', {strict: true});
    if (!feature) return;
    // Both halves of "within 5 feet of the original target AND within your reach". The reach half is
    // measured with the weapon's own range, which the driver stashed alongside the roll.
    let nearbyTargets = tokenUtils.findNearby(workflow.targets.first(), 5, 'ally');
    let realNearbyTargets = tokenUtils.findNearby(workflow.token, currRange, 'enemy').filter(i => nearbyTargets.includes(i));
    if (!realNearbyTargets.length) return;
    let target = realNearbyTargets[0];
    if (realNearbyTargets.length > 1) {
        let picked = await dialogUtils.selectTargetDialog(workflow.item.name, 'CHRISPREMADES.Macros.Maneuvers.SelectTarget', realNearbyTargets);
        if (!picked?.length || !picked[0]) return;
        target = picked[0];
    }
    let activityData = activityUtils.withChangedDamage(feature, superiorityDie, [currDamageType]);
    await workflowUtils.syntheticActivityDataRoll(activityData, workflow.item, workflow.actor, [target]);
}

/**
 * "If the ORIGINAL attack roll would hit the second creature" — the same roll re-checked against a
 * different AC, not a fresh one. Replacing the roll lets midi decide hit/miss normally.
 *
 * ⚠️ `criticalSuccess: Infinity` stops the replayed total from being re-read as a natural 20: the
 * replacement is a flat number, and a 20 there is the first attack's total, not a die face.
 */
async function sweepingAttackAttack({workflow}) {
    let currAttackRoll = workflow.item.flags['chris-premades']?.sweepingAttack?.currAttackRoll;
    if (!currAttackRoll) return;
    let replacementRoll = await new Roll(String(currAttackRoll), {}, {criticalSuccess: Infinity}).evaluate();
    await workflow.setAttackRoll(replacementRoll);
}

export let maneuversDistractingStrike = {
    name: 'Maneuvers: Distracting Strike',
    aliases: ['Maneuver: Distracting Strike'],
    version: '1.0.0',
    rules: 'modern',
    // Edition-stable mechanic. The only wording change is the trigger: 2014 said "hit with a WEAPON
    // attack", 2024 says "hit with an attack roll". Not expressed here because the on-hit gate lives
    // on the shared driver (`superiorityHelper` checks `isAttackType(workflow, 'weaponAttack')`) and
    // applies to every rider — widening it is a driver-level change, not this maneuver's.
    //
    // Driver-spent, so NO `added` passes and no consumption target — the §T83 distinction.
    midi: {
        item: [
            {
                pass: 'rollFinished',
                macro: useDistractingStrike,
                priority: 50
            }
        ]
    }
};
export let distractingStrikeEffect = {
    name: 'Distracting Strike: Effect',
    version: '1.0.0',
    // ⚠️ Must be 'modern' AND exported from macros.js: the marker carries this macro by name, and an
    // effect stamped `rules: 'modern'` is looked up in the modern registry only. See useDistractingStrike.
    rules: 'modern',
    midi: {
        actor: [
            {
                pass: 'targetRollFinished',
                macro: distractingStrikeEffectHit,
                priority: 50
            }
        ]
    }
};
/*
 * T81 BATCH B slice 4c — the last two, and the two that act on an ALLY.
 *
 * Both prompt the other creature's owner rather than deciding for them, which is the house pattern
 * Maneuvering Attack already set: you do not spend someone else's Reaction, or move their character,
 * without asking. Both also carry real 2024 diffs — see each handler.
 */

/**
 * 2024 Commander's Strike: "When you take the Attack action on your turn, you can replace one of
 * your attacks to direct one of your companions to strike. When you do so, choose a willing creature
 * who can see or hear you and expend one Superiority Die. That creature can immediately use its
 * Reaction to make one attack with a weapon or an Unarmed Strike, adding the Superiority Die to the
 * attack's damage roll on a hit."
 *
 * ⚠️ **THE ACTION ECONOMY CHANGED** — 2014 was "as a bonus action"; 2024 replaces one of your
 * attacks. That is expressed in the packData (no activation cost, the rule as an activation
 * condition), exactly as the official item does it. Leaving `bonus` would charge a Bonus Action the
 * player no longer spends.
 *
 * ⚠️ **"see or hear"** — the legacy handler checked sight only. `canSense(…, ['all'])` matches on any
 * detection mode the world defines, which with vision-5e installed includes hearing, and with it
 * absent still covers sight. Same correction Maneuvering Attack got.
 *
 * The ally is left to make their own attack, as the legacy handler does: we mark their Reaction used
 * and hand them the die via a one-shot marker. Rolling their weapon at a target of our choosing
 * would take two decisions away from another player, which is not ours to do.
 */
async function useCommandersStrike({workflow}) {
    let [itemToUse, superiorityDie] = await determineSuperiorityDie(workflow.actor);
    if (!itemToUse?.system.uses.value) return;
    let candidates = workflow.token.scene.tokens.filter(t => {
        if (!t.actor) return false;
        if (t.id === workflow.token.id) return false;
        if (t.disposition !== workflow.token.document.disposition) return false;
        // No Reaction left means they cannot answer the call at all — filtering here keeps them out
        // of the picker rather than letting the fighter pick someone who must then decline.
        if (actorUtils.hasUsedReaction(t.actor)) return false;
        return tokenUtils.canSense(t.object, workflow.token, ['all']);
    }).map(t => t.object);
    if (!candidates.length) {
        genericUtils.notify('CHRISPREMADES.Macros.Maneuvers.NoNearby', 'info');
        return;
    }
    let ally = await pickAlly(workflow, candidates);
    if (!ally) return;
    // "willing" — asked, never assumed. Framed like Maneuvering Attack's prompt: say who is being
    // asked and by whom, since one person often answers for several characters.
    let names = {
        name: ally.name ?? ally.actor.name,
        attacker: veiledName(workflow.token, ally)
    };
    let willUse = await dialogUtils.confirm(
        genericUtils.format('CHRISPREMADES.Macros.Maneuvers.CommanderTitle', names),
        genericUtils.format('CHRISPREMADES.Macros.Maneuvers.CommanderPrompt', names),
        {userId: socketUtils.firstOwner(ally.actor, true)}
    );
    if (!willUse) return;
    let effectData = {
        name: workflow.item.name,
        img: workflow.item.img,
        origin: workflow.item.uuid,
        duration: {
            turns: 1
        },
        // No `changes` at all: the die is appended by the macro below. ⚠️ The legacy entry grants
        // `system.bonuses.weapon.damage` here, which is the §T93 shape — see commandersStrikeAttack.
        changes: [],
        flags: {
            dae: {
                /**
                 * ⚠️ NOT `1Attack`, AND THAT COST A CYCLE TO FIND. DAE deletes a `1Attack` effect
                 * BEFORE midi reaches `damageRollComplete`, so the pass carried by this very effect
                 * never runs: the marker vanishes, the Reaction and the die are both spent, and no
                 * die is appended. Proven as a single-variable A/B in one code state — identical
                 * marker, `1Attack` the only difference: with it the ally's damage was `1 + 1` and
                 * the marker was gone; without it the die appended as its own roll.
                 *
                 * `commandersStrikeAttackHit` owns the lifecycle instead. These are the outer bound:
                 * the ally reacts "immediately", so the offer must not outlive the fighter's turn.
                 */
                specialDuration: [
                    'turnEndSource',
                    'combatEnd'
                ]
            },
            'chris-premades': {
                commandersStrike: {die: superiorityDie}
            }
        }
    };
    effectUtils.addMacro(effectData, 'midi.actor', ['commandersStrikeAttack']);
    // ⚠️ `rules` again, and here it is worse than in Distracting Strike: there is no LEGACY
    // `commandersStrikeAttack` to fall through to, so an unstamped effect looks up undefined and the
    // die silently never lands. See useDistractingStrike for the mechanism.
    await effectUtils.createEffect(ally.actor, effectData, {rules: commandersStrikeAttack.rules});
    await actorUtils.setReactionUsed(ally.actor);
    // ⚠️ THE SPEND IS LAST, AND DELIBERATELY NOT THE ACTIVITY'S. See useBaitAndSwitch.
    await genericUtils.update(itemToUse, {'system.uses.spent': itemToUse.system.uses.spent + 1});
}

/**
 * Add the directed superiority die to the companion's attack.
 *
 * ⚠️ **WHY THIS IS A MACRO AND NOT AN ACTIVE EFFECT.** The legacy handler grants
 * `system.bonuses.weapon.damage = <die>`, and dnd5e's `_processDamagePart` folds that global bonus
 * into damage part **0**, where `BasicRoll.fromConfig` flattens the parts with `parts.join(' + ')`.
 * Nothing in the finished roll can then tell the superiority die apart from the weapon's own dice —
 * which is precisely the §T93 bug Savage Attacker exposed, and it would be *harder* to spot here
 * because it lands on a different actor's card. `bonusDamage` appends a separate roll past
 * `damage.parts.length`, outside every reroll window, and is also the shape RAW describes.
 *
 * ⚠️ This macro OWNS THE MARKER'S LIFECYCLE — see the `specialDuration` note in useCommandersStrike
 * for why DAE cannot. "One attack" means the marker is spent by the attack whether or not it lands;
 * "on a hit" governs only whether the die is appended. A miss that never reaches this pass at all
 * (midi can skip the damage roll) is caught by the turn-end backstop.
 */
async function commandersStrikeAttackHit({trigger: {entity: effect}, workflow}) {
    let die = effect.flags['chris-premades']?.commandersStrike?.die;
    if (!die) return;
    if (!workflowUtils.isAttackType(workflow, 'weaponAttack')) return;
    if (workflow.hitTargets?.size) {
        await workflowUtils.bonusDamage(workflow, die, {damageType: workflow.defaultDamageType});
        await rollUtils.postRerollNote(workflow, {
            source: effect.name,
            kind: 'superiorityDie',
            die,
            total: workflow.damageRolls.at(-1).total
        });
    }
    await genericUtils.remove(effect);
}

/**
 * 2024 Bait and Switch: "When you're within 5 feet of a creature on your turn, you can expend one
 * Superiority Die and switch places with that creature, provided you spend at least 5 feet of
 * movement and the creature is willing and doesn't have the Incapacitated condition. This movement
 * doesn't provoke Opportunity Attacks. Roll the Superiority Die. Until the start of your next turn,
 * you or the other creature (your choice) gains a bonus to AC equal to the number rolled."
 *
 * ⚠️ **THREE REAL 2024 REQUIREMENTS THE LEGACY HANDLER DOES NOT IMPLEMENT:**
 *  1. **"spend at least 5 feet of movement"** — reuses slice 3's `satisfiesMovementRequirement`,
 *     which already carries the trap that core records movement history ONLY for a combatant in a
 *     STARTED combat (so the requirement is waived outside combat rather than silently always false).
 *  2. **"doesn't have the Incapacitated condition"**.
 *  3. **"until the start of your next turn"** — the legacy effect is a bare `rounds: 1`, which
 *     expires on a round boundary instead of on the fighter's own turn. Same correction Evasive
 *     Footwork needed.
 *
 * ⚠️ The swap is written as a **displacement**, not a walk: RAW says it "doesn't provoke Opportunity
 * Attacks", and under v13's movement pipeline a plain x/y update is a real move that region and OA
 * watchers see.
 *
 * ⚠️ The official item ships **twelve** pre-baked "Baited AC +N" effects, one per die value, because
 * a static encoding cannot express "equal to the number rolled". Rolling it here is both simpler and
 * correct for a d10/d12 Battle Master.
 */
async function useBaitAndSwitch({workflow}) {
    if (workflow.targets.size !== 1) return;
    let targetToken = workflow.targets.first();
    if (targetToken.id === workflow.token.id) return;
    if (targetToken.document.disposition * workflow.token.document.disposition < 0) return;
    let [itemToUse, superiorityDie] = await determineSuperiorityDie(workflow.actor);
    if (!itemToUse?.system.uses.value) return;
    if (tokenUtils.checkIncapacitated(targetToken)) {
        genericUtils.notify('CHRISPREMADES.Macros.Maneuvers.BaitSwitchIncapacitated', 'info');
        return;
    }
    let combatant = workflow.token?.document?.combatant;
    if (!satisfiesMovementRequirement({
        historyRecorded: !!combatant && combatant.parent?.started === true,
        movementHistory: workflow.token?.document?.movementHistory,
        minimumDistance: canvas?.grid?.distance
    })) {
        genericUtils.notify('CHRISPREMADES.Macros.Maneuvers.BaitSwitchNoMovement', 'info');
        return;
    }
    // "the creature is willing" — asked, not inferred from disposition. Swapping moves someone
    // else's character, which is not a decision to make for them.
    let names = {
        name: targetToken.name ?? targetToken.actor.name,
        attacker: veiledName(workflow.token, targetToken)
    };
    let willing = await dialogUtils.confirm(
        genericUtils.format('CHRISPREMADES.Macros.Maneuvers.BaitSwitchTitle', names),
        genericUtils.format('CHRISPREMADES.Macros.Maneuvers.BaitSwitchPrompt', names),
        {userId: socketUtils.firstOwner(targetToken.actor, true)}
    );
    if (!willing) return;
    let superiorityRoll = await new Roll(superiorityDie, workflow.actor.getRollData()).evaluate();
    await superiorityRoll.toMessage({
        rollType: 'roll',
        speaker: ChatMessage.implementation.getSpeaker({token: workflow.token}),
        flavor: workflow.item.name
    });
    let toTarget = await dialogUtils.buttonDialog(workflow.item.name, 'CHRISPREMADES.Macros.Maneuvers.BaitSwitchAC', [
        ['CHRISPREMADES.Generic.You', false],
        ['DND5E.Target', true]
    ]);
    let effectData = {
        name: workflow.item.name,
        img: workflow.item.img,
        origin: workflow.item.uuid,
        duration: {
            rounds: 1
        },
        changes: [
            {
                key: 'system.attributes.ac.bonus',
                mode: 2,
                value: superiorityRoll.total,
                priority: 20
            }
        ],
        flags: {
            dae: {
                specialDuration: [
                    'turnStartSource'
                ]
            }
        }
    };
    await genericUtils.updateEmbeddedDocuments(workflow.token.scene, 'Token', [
        {_id: workflow.token.document.id, x: targetToken.document.x, y: targetToken.document.y},
        {_id: targetToken.document.id, x: workflow.token.document.x, y: workflow.token.document.y}
    ], {teleport: true, forced: true, action: 'displace'});
    await effectUtils.createEffect(toTarget ? targetToken.actor : workflow.actor, effectData);
    /**
     * ⚠️ THE DIE IS SPENT HERE, LAST — NOT BY THE ACTIVITY'S CONSUMPTION TARGET, AND THAT IS THE
     * THIRD SPENDING PATTERN IN THIS FILE.
     *
     * The on-hit riders are spent by the driver; Parry, Rally, Feinting and Lunging are spent by
     * their activity's own consumption. Neither works here: these two are the only maneuvers whose
     * gates can legitimately REFUSE after the use has started — the movement and Incapacitated
     * checks above, and the other creature answering "no". An activity-level target fires before
     * any of that, so a refusal cost a die and did nothing. Observed live: the movement gate
     * declined correctly and Combat Superiority still went 3 -> 2.
     *
     * Deferring makes a refusal zero-footprint, which is the principle already locked for
     * [[informed-reroll-design]] — defer consequences, never apply-then-reverse. Refunding the die
     * would have been exactly the shape that principle rejects.
     *
     * ⚠️ Consequence to know: with no consumption target these items must NOT register the §T83
     * `added` re-pointer, because `correctActivityItemConsumption` writes `consumption.targets[0]`
     * unconditionally and throws on an empty array.
     *
     * Residual cosmetic: a refused use still posts its chat card, because midi builds that inside
     * `MidiActivityMixin.use()` before any pass runs. Harmless here — the activation costs no
     * action, so the card is the only trace.
     */
    await genericUtils.update(itemToUse, {'system.uses.spent': itemToUse.system.uses.spent + 1});
}

export let maneuversCommandersStrike = {
    name: 'Maneuvers: Commander\'s Strike',
    aliases: ['Maneuver: Commander\'s Strike'],
    version: '1.0.0',
    rules: 'modern',
    // ✅ REAL 2024 DIFF, and the biggest one in Batch B: this REPLACES ONE OF YOUR ATTACKS (2014 was
    // a Bonus Action). Encoded in the packData as no activation cost plus the rule as an activation
    // condition, which is how the official item expresses it.
    //
    // ⚠️ Spends its die IN THE HANDLER, last, so it registers NO `added` passes and declares no
    // consumption target — see useBaitAndSwitch for why deferring is load-bearing here.
    midi: {
        item: [
            {
                pass: 'rollFinished',
                macro: useCommandersStrike,
                priority: 50
            }
        ]
    },
};
export let commandersStrikeAttack = {
    name: 'Commander\'s Strike: Directed Attack',
    version: '1.0.0',
    // ⚠️ Must be 'modern' AND exported from macros.js — and unlike Distracting Strike's marker there
    // is no legacy entry of this name to fall through to, so getting it wrong means the die simply
    // never lands. See useCommandersStrike.
    rules: 'modern',
    midi: {
        actor: [
            {
                pass: 'damageRollComplete',
                macro: commandersStrikeAttackHit,
                priority: 50
            }
        ]
    }
};
export let maneuversBaitAndSwitch = {
    name: 'Maneuvers: Bait and Switch',
    aliases: ['Maneuver: Bait and Switch'],
    version: '1.0.0',
    rules: 'modern',
    // ✅ THREE REAL 2024 REQUIREMENTS the legacy handler never implemented — the movement spend, the
    // Incapacitated exclusion, and "until the start of your next turn". See useBaitAndSwitch.
    //
    // ⚠️ Spends its die IN THE HANDLER, last, so it registers NO `added` passes and declares no
    // consumption target — see useBaitAndSwitch for why deferring is load-bearing here.
    midi: {
        item: [
            {
                pass: 'rollFinished',
                macro: useBaitAndSwitch,
                priority: 50
            }
        ]
    },
};
export let maneuversSweepingAttack = {
    name: 'Maneuvers: Sweeping Attack',
    aliases: ['Maneuver: Sweeping Attack'],
    version: '1.0.0',
    rules: 'modern',
    // ⚠️ Deliberately NOT in `modernTriggerManeuvers`: `superiorityHelper` appends it itself, but
    // only when the attack is `mwak`, which is what 2024's "with a melee attack roll" requires.
    // Listing it here would offer it on ranged attacks too.
    //
    // Driver-spent (the helper decrements the die after `completeItemUse`), so no consumption target
    // and no `added` passes — but it DOES need `activityIdentifiers`, for a different reason than
    // Parry and Rally do: `getActivityByIdentifier(item, 'sweepingAttackAttack', {strict: true})` is
    // the only way the handler reaches its own hidden attack activity.
    midi: {
        item: [
            {
                pass: 'rollFinished',
                macro: useSweepingAttack,
                priority: 50,
                activities: ['maneuversSweepingAttack']
            },
            {
                pass: 'postAttackRoll',
                macro: sweepingAttackAttack,
                priority: 50,
                activities: ['sweepingAttackAttack']
            }
        ]
    }
};

// ⚠️ THE DRIVER. Without this the three maneuvers above are inert on a 2024 sheet — nothing invokes
// them. CPR does not activate maneuvers from the hotbar or the HUD: `superiorityDice` is an
// ACTOR-level midi macro on `damageRollComplete`, so after any weapon attack's damage it asks
// "perform a maneuver?", adds the superiority die to THAT attack's damage roll
// (`workflowUtils.bonusDamage` — which is what 2024 RAW's "Add the Superiority Die to the attack's
// damage roll" actually describes), runs the chosen maneuver item, and spends the die. Registered
// legacy-only upstream, exactly like the maneuvers themselves.
//
// Reused verbatim: the helper is edition-agnostic (it reads
// `actor.system.scale['battle-master']['combat-superiority-die']` and the actor's own maneuver
// items). ⚠️ That scale key is the DDB parse's; a sheet built from the official PHB 2024 compendium
// uses `battle-master.superiority.die` instead and would silently fall back to d6. Not a problem for
// Xender (DDB-imported), but it is the thing to check first if a maneuver ever rolls a stray d6.
/**
 * The 2024 on-hit riders — the maneuvers whose die is spent on an attack you have just landed, so
 * the driver can offer them at `damageRollComplete`.
 *
 * ⚠️ This exists as its OWN list rather than reusing the legacy one for a single reason: 2024 drops
 * **Grappling Strike**, and the legacy array still legitimately serves the 2014 line where that
 * maneuver exists. Deleting it there would break 2014; leaving it here would offer a maneuver the
 * modern ruleset does not have. Everything else in the legacy list is still a correct 2024 on-hit
 * rider — diffed one by one against `dnd-players-handbook.classes` on 2026-07-29.
 *
 * ⚠️ **Sweeping Attack is deliberately absent**: `superiorityHelper` appends it itself when the
 * attack is `mwak`, matching 2024's "when you hit a creature with a MELEE attack roll".
 *
 * ⚠️ Not on-hit and therefore correctly NOT here: Precision Attack (miss-only in 2024, and it rides
 * midi's `optional.…attack.fail.*` channel, not this driver), Riposte and Parry (Reactions),
 * Ambush / Commanding Presence / Evasive Footwork / Tactical Assessment (no attack involved), and
 * Feinting / Lunging (their die lands on a LATER attack — the pending-die tracker, Batch B slice 2).
 */
export const modernTriggerManeuvers = [
    'maneuversDisarmingAttack',
    'maneuversDistractingStrike',
    'maneuversGoadingAttack',
    'maneuversManeuveringAttack',
    'maneuversMenacingAttack',
    'maneuversPushingAttack',
    'maneuversTripAttack'
];
const PENDING_FLAG = 'superiorityDie';

/**
 * Bank a superiority die against a LATER attack this turn (Feinting Attack; Lunging Attack in
 * slice 3). The die is spent by the maneuver's own consumption when it is used, so what lives here
 * is only the promise to append it once a qualifying attack lands.
 *
 * ⚠️ Built at runtime rather than in packData because the advantage change has to name the chosen
 * target's token id, which does not exist until the maneuver is used. Same reason `vex()` in
 * `mechanics/masteries.js` builds its effect in code, and this deliberately copies that shape.
 *
 * @param {object} workflow the maneuver's own workflow
 * @param {object} options
 * @param {string} options.identifier   the maneuver's CPR identifier
 * @param {string} options.die          e.g. "d8"
 * @param {Token} [options.targetToken] reserve the die for this creature only
 * @param {boolean} [options.requiresMelee] only a melee attack may consume it
 * @param {boolean} [options.grantAdvantage] also grant advantage against that target
 */
async function bankSuperiorityDie(workflow, {identifier, die, targetToken, requiresMelee = false, requiresMovement = false, grantAdvantage = false}) {
    let changes = [];
    if (grantAdvantage && targetToken) {
        // The `vex()` idiom: a conditional midi advantage flag scoped to one token id. midi
        // evaluates the expression with `workflow` in scope at attack time.
        changes.push({
            key: 'flags.midi-qol.advantage.attack.all',
            mode: 2,
            value: 'workflow.targets.first().id === "' + targetToken.id + '"',
            priority: 20
        });
    }
    let effectData = {
        name: workflow.item.name,
        img: workflow.item.img,
        origin: workflow.item.uuid,
        changes,
        duration: {},
        flags: {
            dae: {
                // "this turn" — the maneuver is a Bonus Action on your own turn, so the promise dies
                // with that turn. (Contrast Evasive Footwork's `turnStartSource`, which is "until the
                // START of your next turn".) `combatEnd` is the same belt-and-braces vex uses.
                specialDuration: ['turnEndSource', 'combatEnd'],
                stackable: 'multi',
                showIcon: true
            },
            'chris-premades': {
                [PENDING_FLAG]: {
                    pending: {
                        identifier,
                        name: workflow.item.name,
                        die,
                        targetId: targetToken?.id,
                        requiresMelee,
                        requiresMovement
                    }
                }
            }
        }
    };
    await effectUtils.createEffect(workflow.actor, effectData, {identifier});
}

/**
 * Spend a banked die on the attack that just hit, if one qualifies.
 * @returns {Promise<boolean>} true when a die was consumed — the caller must then NOT offer another
 *                             maneuver, because RAW allows only one per attack.
 */
async function consumePendingSuperiorityDie(workflow) {
    let effects = actorUtils.getEffects(workflow.actor)
        .filter(i => i.flags['chris-premades']?.[PENDING_FLAG]?.pending);
    if (!effects.length) return false;
    let combatant = workflow.token?.document?.combatant;
    let attack = {
        actionType: workflowUtils.getActionType(workflow),
        hitTargetIds: [...(workflow.hitTargets ?? [])].map(i => i.id),
        // Core clears movementHistory at the start of each combatant's turn, so this is already
        // scoped to "this turn" with no bookkeeping of ours -- but it only RECORDS for a combatant
        // in a started combat, so mirror that gate rather than reading an always-empty array.
        movedThisTurn: satisfiesMovementRequirement({
            historyRecorded: !!combatant && combatant.parent?.started === true,
            movementHistory: workflow.token?.document?.movementHistory,
            minimumDistance: canvas?.grid?.distance
        })
    };
    let byPending = new Map(effects.map(i => [i.flags['chris-premades'][PENDING_FLAG].pending, i]));
    let chosen = selectPendingDie([...byPending.keys()], attack);
    if (!chosen) return false;
    await workflowUtils.bonusDamage(workflow, chosen.die, {damageType: workflow.defaultDamageType});
    // Same explanation the driver posts, so the damage ⓘ accounts for every die on the card.
    await rollUtils.postRerollNote(workflow, {
        source: chosen.name,
        kind: 'superiorityDie',
        die: chosen.die,
        total: workflow.damageRolls.at(-1).total
    });
    await genericUtils.remove(byPending.get(chosen));
    return true;
}

async function modernHit({workflow}) {
    // A banked die IS this attack's maneuver — RAW caps it at one per attack, so a consumed die
    // must suppress the driver's offer rather than stack with it.
    if (await consumePendingSuperiorityDie(workflow)) return;
    await superiorityHelper(workflow, {triggerManeuvers: modernTriggerManeuvers});
}

/**
 * 2024 Feinting Attack: "As a Bonus Action, you can expend one Superiority Die to feint, choosing
 * one creature within 5 feet of yourself as your target. You have Advantage on your next attack roll
 * against that target this turn. If that attack hits, add the Superiority Die to the attack's damage
 * roll."
 *
 * ⚠️ We automate BOTH halves. The official PHB item says outright that it "does not automate the
 * Advantage" and ships a Damage activity you fire by hand after the hit; riding the tracker means
 * the die lands on the right attack automatically and cannot be spent twice.
 */
async function useFeintingAttack({workflow}) {
    if (workflow.targets.size !== 1) return;
    let [, superiorityDie] = await determineSuperiorityDie(workflow.actor);
    if (!superiorityDie) return;
    await bankSuperiorityDie(workflow, {
        identifier: 'maneuversFeintingAttack',
        die: superiorityDie,
        targetToken: workflow.targets.first(),
        grantAdvantage: true
    });
}
export let superiorityDice = {
    name: 'Superiority Dice',
    aliases: ['Combat Superiority'],
    // 1.1.0 — the modern line no longer borrows the legacy driver's midi passes wholesale; it runs
    // the same helper with its own trigger list (see above). Behaviour is identical except that
    // Grappling Strike is no longer offered on a 2024 sheet.
    version: '1.1.0',
    rules: 'modern',
    midi: {
        actor: [
            {
                pass: 'damageRollComplete',
                macro: modernHit,
                priority: 50
            }
        ]
    }
};
