import {actorUtils, constants, dialogUtils, effectUtils, genericUtils, itemUtils, socketUtils, tokenUtils, workflowUtils} from '../../../../../utils.js';
import {determineSuperiorityDie} from '../../../../2014/classFeatures/fighter/battleMaster/superiorityDice.js';
import {maneuversGoadingAttack as goadingAttackLegacy} from '../../../../2014/classFeatures/fighter/battleMaster/maneuvers.js';
import {superiorityDice as superiorityDiceLegacy} from '../../../../2014/classFeatures/fighter/battleMaster/superiorityDice.js';

// CPR's 23 maneuvers are registered ONLY in the legacy registry, and premade lookup picks the pack
// by the item's ruleset (`integrations/ddbi.js` maps 2014 -> legacy, 2024 -> modern), so a 2024-rules
// Battle Master could never match any of them. These are the first three ported forward, chosen
// because they are the ones actually on the table.

// 2024 PHB, Riposte: "When a creature misses you with a melee attack roll, you can take a Reaction
// and expend one Superiority Die to make a melee attack roll with a weapon or an Unarmed Strike
// against the creature. If you hit, add the Superiority Die to the attack's damage."
//
// ⚠️ Upstream binds `maneuversRiposte` to `useBrace` (2014 maneuvers.js:597) — Brace's handler. The
// two are mechanically near-identical, so it works by accident rather than being broken, but it is a
// maintenance trap: tuning Brace silently retunes Riposte. The modern entry gets its own handler,
// which also adds the Unarmed Strike option 2024 introduced. Legacy stays weapon-only on purpose —
// 2014 Riposte reads "melee weapon attack".
async function useRiposte({workflow}) {
    if (workflow.targets.size !== 1) return;
    let attacks = workflow.token.actor.items.filter(i => {
        if (constants.unarmedAttacks.includes(genericUtils.getIdentifier(i))) return true;
        return i.type === 'weapon' && i.system.equipped && i.system.activities.getByType('attack').some(j => j.actionType === 'mwak');
    });
    if (!attacks.length) return;
    let [itemToUse, superiorityDie] = await determineSuperiorityDie(workflow.actor);
    if (!itemToUse?.system.uses.value) return;
    let selected;
    if (attacks.length === 1) {
        selected = attacks[0];
    } else {
        selected = await dialogUtils.selectDocumentDialog(workflow.item.name, 'CHRISPREMADES.Macros.Antagonize.SelectWeapon', attacks);
    }
    if (!selected) return;
    let effectData = {
        name: workflow.item.name,
        img: workflow.item.img,
        origin: workflow.item.uuid,
        changes: [
            {
                key: 'system.bonuses.mwak.damage',
                mode: 2,
                value: superiorityDie,
                priority: 20
            }
        ]
    };
    let effect = await effectUtils.createEffect(workflow.actor, effectData);
    /**
     * ⚠️ BOTH FLAGS ARE LOAD-BEARING.
     *
     * `maneuverAttack` — marks this as an attack GENERATED BY a maneuver, so the superiority driver
     * does not offer a second maneuver on it. RAW, "You can use only one maneuver per attack" (2024
     * Combat Superiority, verbatim); Riposte is itself the maneuver on this attack.
     *
     * `notReaction` — ⚠️ WITHOUT THIS THE PLAYER IS ASKED TO SPEND THEIR REACTION TWICE.
     * With midi's `recordAOO` on (this world runs "all"), midi flags ANY in-combat attack made
     * outside the actor's own turn as an opportunity attack: `workflow.AoO = true` and
     * `itemUsesReaction = true`. A Riposte counter-attack is by definition out-of-turn, so midi tries
     * to consume a reaction that the Riposte item itself has ALREADY consumed — surfacing as
     * "You have used your reaction this round. Do you want to proceed anyway?" between the weapon
     * choice and the attack. `notReaction` skips that whole reaction/AoO block.
     * Established in T3 — see [[midiqol-invocation-and-autoroll]]; the same heuristic is why an
     * out-of-turn attack also skips midi's out-of-range abort.
     */
    await workflowUtils.syntheticItemRoll(selected, [workflow.targets.first()], {
        options: {workflowOptions: {maneuverAttack: true, notReaction: true}}
    });
    if (effect) await genericUtils.remove(effect);

    /**
     * ⚠️ DO NOT UNCONDITIONALLY SPEND HERE — THAT IS A DOUBLE SPEND.
     *
     * The activity carries an `itemUses` consumption target pointing at the actor's Superiority
     * Dice item (re-pointed at add-time by `added`, see T83), so using Riposte ALREADY spends one
     * die. `determineSuperiorityDie` returns that same item for an ordinary Battle Master, so
     * decrementing again costs two dice per Riposte.
     *
     * It read as correct for a long time only because the consumption target was an unresolvable
     * compendium placeholder — dnd5e silently spent nothing and this line was the sole spend.
     * Repairing the target (T83) armed the second one. Upstream's legacy entry has the same shape.
     *
     * The manual decrement still has one real job: `determineSuperiorityDie` may pick a DIFFERENT
     * pool (Martial Adept, Superior Technique fighting style), which the activity's fixed target
     * cannot express. Spend by hand only in that case.
     */
    let consumedTarget = workflow.activity?.consumption?.targets?.find(i => i.type === 'itemUses')?.target;
    if (consumedTarget !== itemToUse.id) {
        await genericUtils.update(itemToUse, {'system.uses.spent': itemToUse.system.uses.spent + 1});
    }
}

/**
 * Offer Riposte automatically when a creature MISSES this actor with a melee attack roll.
 *
 * WHY A TARGET-SIDE PASS: Riposte was registered only on `midi.item` / `rollFinished`, which fires
 * on the holder's OWN use — so nothing watched attacks made *against* them and the reaction had to
 * be invoked by hand. This mirrors what upstream already does for **Parry**, which reacts from
 * `midi.actor` / `targetApplyDamage`; the two differ only in trigger (miss vs damage), which is why
 * the gate below is shared rather than the whole handler.
 *
 * RAW (2024 PHB, verbatim): "When a creature misses you with a melee attack roll, you can take a
 * Reaction and expend one Superiority Die to make a melee attack roll…". Note **melee attack roll**,
 * not melee *weapon* attack — a melee spell attack qualifies, which `isAttackType(…, 'meleeAttack')`
 * already covers.
 */
async function offerRiposte({trigger, workflow}) {
    let item = trigger.entity;
    // The miss is the whole trigger: this pass runs for every target, hit or not.
    if (workflow.hitTargets?.has(trigger.token)) return;
    if (!await canReactWithManeuver(item, workflow)) return;
    if (!await dialogUtils.confirmUseItem(item, {userId: socketUtils.firstOwner(item.parent, true)})) return;
    // Target the attacker — `useRiposte` reads `workflow.targets` to pick who to strike back at.
    // `consumeResources` so the activity's own consumption spends the die exactly once.
    await workflowUtils.syntheticItemRoll(item, [workflow.token], {consumeResources: true});
}

/**
 * The shared gate for a REACTION maneuver offered from the target side (Riposte now, Parry when
 * Batch B lands). Deliberately does NOT check hit/miss — that is the per-maneuver trigger.
 * @returns {Promise<boolean>}
 */
async function canReactWithManeuver(item, workflow) {
    if (!workflowUtils.isAttackType(workflow, 'meleeAttack')) return false;
    let [itemToUse] = await determineSuperiorityDie(item.parent);
    if (!itemToUse?.system.uses.value) return false;
    if (actorUtils.hasUsedReaction(item.parent)) return false;
    return true;
}

// A creature's name as the ASKED CHARACTER would know it, not as the GM does.
//
// ⚠️ The prompt is composed GM-side and socketed to whoever answers it, so the veil module's own
// `effectiveViewer()` is the wrong frame — on a GM client it returns `{omniscient: true}` and a
// veiled NPC's true name goes straight into the dialog text. Framing it on the ALLY token asks the
// question that actually matters ("can the character being asked tell who that is?") and gives the
// same answer no matter which user reads the dialog.
//
// `{omniscient: false, refs: [token]}` is the module's own supported viewer shape — it is exactly
// what `computeEffectiveViewer` builds for a GM with a PC selected. A no-op for PCs, and for NPCs
// when the module is disabled or the creature is already identified.
// ⚠️ The effect description bakes this in at creation time, so a name resolved as a placeholder
// stays a placeholder even if the ally later closes the distance. Acceptable as a snapshot.
function veiledName(token, viewerToken) {
    let veil = game.modules.get('npc-name-veil')?.api;
    if (!veil?.getDisplayName) return token.name;
    return veil.getDisplayName(token, {omniscient: false, refs: [viewerToken]});
}

// Ally selection, on canvas where possible. Argon's own picker is what the player already uses to
// choose an attack target, so picking the ally the same way is one less modality — but it only
// exists while the HUD is running, and a sheet click has no picker at all (that gap is T79). The
// dialog list stays as the fallback so the sheet path is never dead.
async function pickAlly(workflow, candidates) {
    let picker = game.modules.get('enhancedcombathud')?.active ? game.modules.get('enhancedcombathud').api?.runTargetPicker : null;
    if (picker) {
        // ⚠️ runTargetPicker resolves to a BOOLEAN (true = completed, false = cancelled), NOT to the
        // tokens picked — the selection is left in `game.user.targets`. Assuming it returned tokens
        // made this whole branch a silent no-op: `Array.from(true)` is `[]`, so no ally was ever
        // chosen, no confirmation was ever raised, and no exemption was ever applied. It failed
        // without an error, which is why it looked like it worked.
        let completed = await picker({
            token: workflow.token,
            targets: 1,
            label: genericUtils.translate('CHRISPREMADES.Macros.Maneuvers.SelectAlly'),
            item: workflow.item
        });
        if (!completed) return undefined;
        let chosen = Array.from(game.user.targets)[0];
        if (!chosen) return undefined;
        // The picker targets any token — deliberately, since RAW leaves the choice to the player and
        // Vittorio asked to trust them. Warn on a pick outside the see-or-hear ally set rather than
        // refusing it, so an unusual-but-legal choice still goes through.
        if (!candidates.some(c => c.id === chosen.id)) {
            genericUtils.notify('CHRISPREMADES.Macros.Maneuvers.NotAnAlly', 'warn');
        }
        return chosen;
    }
    let picked = await dialogUtils.selectTargetDialog(workflow.item.name, 'CHRISPREMADES.Macros.Maneuvers.SelectAlly', candidates);
    return picked?.[0];
}

// 2024 PHB, Maneuvering Attack: "...choose a willing creature who can see or hear you. That creature
// can use its Reaction to move up to half its Speed without provoking Opportunity Attacks from the
// target of your attack."
//
// Two changes from the legacy handler:
//   1. "see OR hear" — legacy checked sight only (`tokenUtils.canSee`). `canSense(..., ['all'])`
//      matches on any detection mode the world defines, which with vision-5e installed includes its
//      `hearing` mode; with vision-5e absent it still covers sight, i.e. never worse than legacy.
//   2. The OA exemption is now real. The chosen ally gets `flags.midi-qol.oaManeuveringAttack`
//      carrying the attacked creature's token id, which our GPS fork's opportunityAttack.js skips on
//      — the same per-pair mechanism upstream GPS already uses for the Mobile feat and Fancy
//      Footwork. Written as an ActiveEffect CHANGE, not a stored flag, so removing the effect removes
//      the exemption; nothing has to remember to clean up.
//
// ⚠️ "The target of your attack" is read from the workflow BEFORE the ally retarget below, i.e. it is
// whoever Xender still has targeted when he uses the maneuver — true in the normal flow (attack, then
// use the maneuver), but it is an inference, not something the item records. With no target held, the
// ally is still designated and still spends its Reaction; only the OA exemption is skipped.
async function useManeuveringAttack({workflow}) {
    let attackedToken = workflow.targets.first();
    let candidates = workflow.token.scene.tokens.filter(t => {
        if (!t.actor) return false;
        if (t.id === workflow.token.id) return false;
        if (t.disposition !== workflow.token.document.disposition) return false;
        return tokenUtils.canSense(t.object, workflow.token, ['all']);
    }).map(t => t.object);
    if (!candidates.length) {
        await workflowUtils.updateTargets(workflow, []);
        return;
    }
    let ally = await pickAlly(workflow, candidates);
    if (!ally) {
        await workflowUtils.updateTargets(workflow, []);
        return;
    }
    // The prompt is often read by someone holding several characters at once — the GM covering absent
    // players, most of all — so it has to say WHO is being asked and WHY, not just "spend your
    // reaction?". Title carries the ally's token name, mirroring the Alert feat's `Alert — {name}`
    // ([[dnd5e-alert-initiative-swap]]); the body restates the whole situation, since the ally may not
    // have been watching the attack that triggered it.
    // ⚠️ Names are token names (falling back to actor names), which is what the players see on the
    // board. A veiled NPC's true name would surface here — acceptable, since the ally is being told
    // about a creature that just attacked in front of them, but it is the one leak worth knowing about.
    let names = {
        name: ally.name ?? ally.actor.name,
        attacker: veiledName(workflow.token, ally),
        enemy: attackedToken ? veiledName(attackedToken, ally) : game.i18n.localize('DND5E.Target')
    };
    dialogUtils.confirm(
        genericUtils.format('CHRISPREMADES.Macros.Maneuvers.ManeuveringTitle', names),
        genericUtils.format('CHRISPREMADES.Macros.Maneuvers.ManeuveringPrompt', names),
        {userId: socketUtils.firstOwner(ally.actor, true)}
    ).then(async choice => {
        if (!choice) return;
        actorUtils.setReactionUsed(ally.actor);
        if (!attackedToken || attackedToken.id === ally.id) return;
        await effectUtils.createEffect(ally.actor, {
            name: workflow.item.name,
            img: workflow.item.img,
            origin: workflow.item.uuid,
            // Without an explicit description Visual Active Effects falls back to the origin item's,
            // i.e. the entire feature text. The ally does not need the rules quotation — they need
            // what they may do right now, and against whom.
            description: genericUtils.format('CHRISPREMADES.Macros.Maneuvers.ManeuveringEffect', names),
            duration: {
                rounds: 1
            },
            changes: [
                {
                    key: 'flags.midi-qol.oaManeuveringAttack',
                    mode: 2,
                    value: attackedToken.id,
                    priority: 20
                }
            ],
            flags: {
                dae: {
                    specialDuration: [
                        'turnEndSource'
                    ]
                }
            }
        });
    });
    await workflowUtils.updateTargets(workflow, [ally]);
}

// ⚠️ WITHOUT THIS, A DIRECTLY-USED MANEUVER CANNOT BE SPENT AT ALL (T83, 2026-07-27).
//
// The packData ships its consumption target as a COMPENDIUM UUID placeholder
// (`Compendium.chris-premades.CPRClassFeatures.Item.tr7yGwS1sVVeJVXt`), which is meaningless once
// the item sits on an actor — dnd5e cannot resolve it to anything the character owns, so the
// consumption prompt reports "0 of 1 usage" while Combat Superiority sits there at 4/4. Upstream
// fixes this at add-time by re-pointing the target to the actor's OWN Superiority Dice item, and
// the T56 slice ported the maneuvers without porting that step.
//
// Only maneuvers that carry an item-level consumption target need this, and that is a real
// distinction rather than an oversight: the ON-HIT riders (Goading Attack, Maneuvering Attack, …)
// are spent by the `superiorityDice` DRIVER, which decrements the die itself
// (`2014/.../superiorityDice.js:74`), so they deliberately have no target. Riposte is a Reaction
// used directly from the sheet, so nothing else would ever spend its die.
//
// ⚠️ Do NOT register this on a maneuver with no consumption target — `correctActivityItemConsumption`
// writes `consumption.targets[0].target` unconditionally and would throw on an empty array.
async function added({trigger: {entity: item}}) {
    await itemUtils.correctActivityItemConsumption(item, ['use'], 'superiorityDice');
}

export let maneuversRiposte = {
    name: 'Maneuvers: Riposte',
    // No bare-name alias on purpose: the Monster Manual ships an NPC feat also called "Riposte"
    // (dnd5e.monsterfeatures24 / dnd-monster-manual.features `mmRiposte0000000`), and a bare alias
    // would put this Battle Master automation in front of it. `Maneuver: X` is what our DDB fork's
    // enricher produces, which is what a real 2024 sheet actually carries.
    aliases: ['Maneuver: Riposte'],
    // 1.0.3 — the counter-attack no longer re-asks for a reaction (notReaction, see useRiposte).
    // ⚠️ The version here is the MACRO registry stamp; `isUpToDate` reads it while the packData
    // carries its own. Bump BOTH or an already-deployed item never reports out-of-date.
    version: '1.0.3',
    rules: 'modern',
    // Three passes, matching upstream's legacy registration: `created` covers a fresh add,
    // `itemMedkit` an item-level Medkit run, `actorMunch` a DDB (re-)import. An item already on a
    // sheet before this shipped is only repaired by one of the latter two — see the memory note.
    item: [
        {
            pass: 'created',
            macro: added,
            priority: 55
        },
        {
            pass: 'itemMedkit',
            macro: added,
            priority: 55
        },
        {
            pass: 'actorMunch',
            macro: added,
            priority: 55
        }
    ],
    midi: {
        item: [
            {
                pass: 'rollFinished',
                macro: useRiposte,
                priority: 50
            }
        ],
        // Target-side: fires on THIS actor when someone attacks them, so the reaction is offered
        // without the player having to remember it. `targetAttackRollComplete` is the first pass
        // where hit/miss is known, which is exactly Riposte's trigger.
        actor: [
            {
                pass: 'targetAttackRollComplete',
                macro: offerRiposte,
                priority: 50
            }
        ]
    }
};
export let maneuversGoadingAttack = {
    name: 'Maneuvers: Goading Attack',
    aliases: ['Maneuver: Goading Attack'],
    version: '1.0.0',
    rules: 'modern',
    // Edition-stable: the 2014 and 2024 wordings are identical (Wisdom save, Disadvantage on attacks
    // against anyone but you, until the end of your next turn), so the legacy handler ports verbatim.
    // Worth knowing: this is the only source that implements the Disadvantage at all — the official
    // PHB 2024 item and our DDB enricher both ship a `Goaded` effect with ZERO changes, i.e. a marker.
    midi: {
        item: [
            {
                pass: 'rollFinished',
                macro: goadingAttackLegacy.midi.item[0].macro,
                priority: 50
            }
        ]
    }
};
export let maneuversManeuveringAttack = {
    name: 'Maneuvers: Maneuvering Attack',
    aliases: ['Maneuver: Maneuvering Attack'],
    version: '1.0.0',
    rules: 'modern',
    midi: {
        item: [
            {
                pass: 'preambleComplete',
                macro: useManeuveringAttack,
                priority: 50
            }
        ]
    }
};

// ⚠️ THE DRIVER. Without this the three maneuvers above are inert on a 2024 sheet — nothing invokes
// them. CPR does not activate maneuvers from the hotbar or the HUD: `superiorityDice` is an
// ACTOR-level midi macro on `damageRollComplete`, so after any weapon attack's damage it asks
// "perform a maneuver?", adds the superiority die to THAT attack's damage roll
// (`workflowUtils.bonusDamage` — which is what 2024 RAW's "Add the Superiority Die to the attack's
// damage roll" actually describes), runs the chosen maneuver item, and spends the die. Registered
// legacy-only upstream, exactly like the maneuvers themselves.
//
// Reused verbatim: the helper is edition-agnostic (it reads
// `actor.system.scale['battle-master']['combat-superiority-die']` and the actor's own maneuver
// items). ⚠️ That scale key is the DDB parse's; a sheet built from the official PHB 2024 compendium
// uses `battle-master.superiority.die` instead and would silently fall back to d6. Not a problem for
// Xender (DDB-imported), but it is the thing to check first if a maneuver ever rolls a stray d6.
export let superiorityDice = {
    name: 'Superiority Dice',
    aliases: ['Combat Superiority'],
    version: '1.0.0',
    rules: 'modern',
    midi: superiorityDiceLegacy.midi
};
